"""
Autogenerated file with autoGenerate.py. Do not modify manually !
"""

from . import c
from . import config
from . import containers
from .containers import TestAsset, TestImage
from . import content
from .content import *

