"""
Configuration of the package behavior
"""
from . import c

coreFileName = "content"
coreFilePath = c.PACKAGE_DIR / f"{coreFileName}.py"

initContent = f"""\"\"\"
Autogenerated file with autoGenerate.py. Do not modify manually !
\"\"\"

from . import c
from . import config
from . import containers
from .containers import TestAsset, TestImage
from . import {coreFileName}
from .{coreFileName} import *

"""
