"""
Autogenerated file with autoGenerate.py. Do not modify manually !
"""

from pathlib import Path

from .containers import TestAsset
    
__all__ = (
   "colorCheckerXrite2014",
   "dragonScene",
)

colorCheckerXrite2014 = TestAsset(
    Path(r"data\colorCheckerXrite2014")
)

dragonScene = TestAsset(
    Path(r"data\dragonScene")
)
