"""
Autogenerated file with autoGenerate.py. Do not modify manually !
"""

from pathlib import Path

from . import c
from .containers import TestAsset
    
__all__ = (
   "colorCheckerXrite2014",
   "dragonScene",
)

colorCheckerXrite2014 = TestAsset(c.DATA_DIR / "colorCheckerXrite2014")

dragonScene = TestAsset(c.DATA_DIR / "dragonScene")
